version: "3.7"

services:
  maria:
    image: mariadb:10.5.8
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=gitproxy
      - MYSQL_ROOT_PASSWORD=root